[colors.bright]
black = "#686868"
blue = "#65bddb"
cyan = "#1be1f7"
green = "#23fe6e"
# magenta = "#f17676"
# magenta = "#cfbafa"
magenta = "#ae9dd1"
red = "#f76868"
white = "#fafafa"
yellow = "#ffd165"

[colors.normal]
black = "#212733"
blue = "#60b8d6"
cyan = "#34d8eb"
green = "#22df61"
# magenta = "#ec7171"
# magenta = "#d4bfff"
magenta = "#8e7db0"
red = "#ed4e4e"
white = "#f8f8f8"
yellow = "#fdcc60"

[colors.primary]
background = "#27272d"
bright_foreground = "#f28779"
foreground = "#cbccc6"

[cursor]
style = "Beam"

[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window.dimensions]
columns = 140
lines = 36
